<?php
/**
 * Copyright 2020 Vipps
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
//@codingStandardsIgnoreFile
/** @var \Vipps\Payment\Block\Monitoring\Buttons $block */
$vippsQuote = $block->getVippsQuote(); ?>
<div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
    <div class="page-actions-inner">
        <div class="page-actions-buttons">
            <button
                    id="action-back"
                    title="Back"
                    type="button"
                    class="action- scalable back"
                    onclick="location.href='<?= $block->getUrl('*/*'); ?>'"
                    data-ui-id="back-button">
                <span><?=  __('Back') ?></span>
            </button>
            <?php if ($block->isRestartVisible()) : ?>
                <button
                        id="action-restart"
                        title type="button"
                        class="action-default primary"
                        onclick="location.href='<?= $block->getUrl('*/*/restart', ['entity_id' => $vippsQuote->getEntityId()]); ?>'">
                    <span><?=  __('Restart Processing') ?></span>
                </button>
            <?php endif; ?>
            <?php if ($block->isCancelVisible()) : ?>
                <button
                        id="action-cancel"
                        title type="button"
                        data-url="<?= $block->getUrl('*/*/cancel', ['entity_id' => $vippsQuote->getEntityId()]); ?>"
                        class="action-scalable action-secondary">
                    <span><?= __('Cancel') ?></span>
                </button>
            <?php endif; ?>
        </div>
    </div>
</div>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/confirm',
        'mage/translate'
    ], function ($, confirmation) {

        $(function () {

            $('#action-cancel').click(function () {

                confirmation({
                    "title": $.mage.__("Are you sure?"),
                    "content": $.mage.__("This procedure can not be undone."),
                    "actions": {
                        "confirm": $.proxy(function () {
                            window.location = $(this).data('url');
                        }, $(this)),
                    }
                });

            });
        });
    });
</script>
